[package]
name = "excelNif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "excelNif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
calamine = "0.24.0"
